### ISSUE TITLE
Problem with nohup snippy-core

### ISSUE THREAD

**Issue by manuss11** [tseemann/mlst#76]
Hello!

I was learning about Nullarbor with that **https://discourse.climb.ac.uk/t/nullarbor-tutorial-automated-bacterial-sequence-mapping-variant-calling-mlst-assignation-and-resistance-screening/32** TUTORIAL, but when I am going to run the last command to compare a group of samples that are more closely related, it doesn't run.

This is the command:
**nohup snippy-core --prefix shigellaflexgroup Sample1/Sample1 Sample10/Sample10 Sample11/Sample11 Sample12/Sample12 Sample2/Sample2 Sample3/Sample3 Sample4/Sample4 Sample5/Sample5 Sample6/Sample6 Sample7/Sample7 Sample8/Sample8 Sample9/Sample9 &**

And the error is:  **nohup: ignoring input and appending output to 'nohup.out'**

I really do not understand why the name of the sample appears repeated. What is the necessary input?

I would really appreciate your help

Regards

**Comment by tseemann** [comment]
Firstly, I did not write that tutorial, and it may be for Nullarbor 1.x and not the current series.

Secondly, `nohup` is not an error. That message is telling you that snippy-core is now running in the background, and its output is being put into the `nohup.out` file instead of printing to the screen.

The sample names are doubled because of the way Nullarbor 1.x used to work. That is no longer the case.
