### ISSUE TITLE
mlst scheme Clostridium perfringens

### ISSUE THREAD

**Issue by martahp** [tseemann/mlst#78]
Before the db included de cperfringens MLST scheme and now is not available

**Comment by tseemann** [comment]
On this master page, C.perf does not exist:
https://pubmlst.org/databases/

But I do see it here:
https://pubmlst.org/cperfringens/

I'll contact @kjolley and find out what has happened.

**Comment by kjolley** [comment]
The C. perfringens database was never formally released on PubMLST. The authors of the legacy scheme originally contacted me asking for the database to be set up - this was set up privately - with no links on the site pointing to its existence (although it was not password protected). At no point since have they asked for it to be made public and they have not responded to E-mails. I did notice that they published and linked to the site but did not inform me of this. They have also not responded to curation requests.

Since then, I have received multiple queries about this database and an offer to further develop a scheme and take over its curation - this is the new database, but this is still in development (hence still not linked from the database page). Again, this has never been formally released.

**Comment by martahp** [comment]
Thanks, but I believe it was, because I have been using the Dr. Seeman´s MLST software with the database of C. perfringens and having the results. If you keep records maybe it can be checked.
Regards,

**Comment by tseemann** [comment]
Thanks @kjolley for the explaination

I don't recall `cperfringens` being in my mlst database. 
I just searched my full git history and there was no mention of it.

Perhaps you added it manually, or a colleague installed it?
